package com.example.ui

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    ARABIC("ar", "Arabic", "العربية")
}

object Strings {
    fun get(key: String, lang: AppLanguage): String {
        val ar = lang == AppLanguage.ARABIC
        return when (key) {
            // App & Nav
            "app_title" -> if (ar) "فيرونيس" else "VEYRONIS"
            "app_subtitle" -> if (ar) "بناء العوالم والمحرر الروائي" else "Worldbuilding & Novelist"
            "nav_dashboard" -> if (ar) "الداشبورد" else "Dashboard"
            "nav_writer" -> if (ar) "المحرر (الكاتب)" else "Writer"
            "nav_settings" -> if (ar) "الإعدادات" else "Settings"
            "nav_characters" -> if (ar) "الشخصيات" else "Characters"
            "nav_codex" -> if (ar) "الموسوعة" else "Codex"
            "nav_timeline" -> if (ar) "الخط الزمني" else "Timeline"
            "nav_events" -> if (ar) "الأحداث" else "Events"
            "nav_graphs" -> if (ar) "الشبكات السببية" else "Graphs"
            "nav_rules" -> if (ar) "قوانين العالم" else "World Rules"
            "nav_search" -> if (ar) "البحث العام" else "Search"

            // Common / Actions
            "add" -> if (ar) "إضافة" else "Add"
            "edit" -> if (ar) "تعديل" else "Edit"
            "delete" -> if (ar) "حذف" else "Delete"
            "save" -> if (ar) "حفظ" else "Save"
            "cancel" -> if (ar) "إلغاء" else "Cancel"
            "close" -> if (ar) "إغلاق" else "Close"
            "search" -> if (ar) "بحث" else "Search"
            "filter_all" -> if (ar) "الكل" else "All"
            "status" -> if (ar) "الحالة" else "Status"
            "active" -> if (ar) "نشط" else "Active"
            "type" -> if (ar) "النوع" else "Type"
            "category" -> if (ar) "التصنيف" else "Category"
            "details" -> if (ar) "التفاصيل" else "Details"
            "confirm" -> if (ar) "تأكيد" else "Confirm"
            "none" -> if (ar) "لا يوجد" else "None"

            // Language & Settings
            "language_settings" -> if (ar) "إعدادات اللغة والواجهة" else "Language & Interface"
            "select_language" -> if (ar) "اختر لغة التطبيق المفضلة:" else "Select preferred application language:"
            "english" -> "English"
            "arabic" -> "العربية"
            "enforce_ltr_note" -> if (ar) "اتجاه الواجهة مثبت من اليسار إلى اليمين (LTR) لمنع التشتت البصري" else "Interface direction is pinned Left-to-Right (LTR) for visual stability"
            "data_management" -> if (ar) "إدارة البيانات والمشاريع" else "Data & Project Management"
            "delete_sample_desc" -> if (ar) "تفريغ ومسح كافة البيانات والعناصر التجريبية للبدء بمشروع جديد كلياً" else "Purge all seeded demo stories, characters, and events for a clean slate"
            "clear_sample_data" -> if (ar) "مسح البيانات التجريبية" else "Clear Sample & Demo Data"
            "confirm_delete" -> if (ar) "تأكيد مسح البيانات" else "Confirm Data Purge"
            "delete_warning_msg" -> if (ar) "هل أنت متأكد من مسح جميع العناصر التجريبية؟ لا يمكن التراجع عن هذا الإجراء." else "Are you sure you want to delete all sample items? This cannot be undone."
            "settings_title" -> if (ar) "إعدادات التطبيق والمخطوطة" else "App & Manuscript Settings"
            "export_title" -> if (ar) "تصدير المخطوطة" else "Publishing & Manuscript Export"
            "export_subtitle" -> if (ar) "تصدير العمل إلى تنسيقات نشر قياسية" else "Compile manuscript into standard publishing formats"
            "author_name" -> if (ar) "اسم المؤلف" else "Author Name"
            "export_btn" -> if (ar) "تجميع وتصدير" else "Compile & Export"
            "system_status" -> if (ar) "حالة النظام والإصدار" else "System Integrity & Release"
            "version" -> if (ar) "الإصدار" else "Version"

            // Dashboard
            "current_manuscript" -> if (ar) "المخطوطة الحالية" else "Active Manuscript"
            "overall_progress" -> if (ar) "التقدم الإجمالي" else "Overall Progress"
            "words_count" -> if (ar) "كلمة" else "words"
            "target" -> if (ar) "الهدف" else "Target"
            "scenes" -> if (ar) "مشاهد" else "Scenes"
            "chapters" -> if (ar) "فصول" else "Chapters"
            "characters_count" -> if (ar) "شخصية" else "Characters"
            "codex_count" -> if (ar) "موسوعة" else "Codex"
            "events_count" -> if (ar) "أحداث" else "Events"
            "warnings_count" -> if (ar) "تنبيهات الاتساق" else "Continuity Alerts"
            "no_warnings" -> if (ar) "لا توجد أخطاء في التسلسل الزمني أو السببية" else "Timeline continuity and causal links are pristine"
            "open_writer" -> if (ar) "فتح المحرر" else "Open Manuscript Writer"
            "clean_slate" -> if (ar) "مشروع نظيف وجاهز للكتابة" else "Clean workspace ready for your story"

            // Writer
            "scene_title" -> if (ar) "عنوان المشهد..." else "Scene Title..."
            "start_writing_hint" -> if (ar) "ابدأ في كتابة فصولك هنا...\n\nيقوم فيرونيس تلقائياً برصد الشخصيات، الكيانات الموسوعية، وفيزياء العالم، والاتساق الزمني والسببي أثناء كتابتك." else "Begin weaving your chapter here...\n\nVeyronis automatically tracks characters, lorebook entities, world physics, and temporal causality as you write."
            "autosaved" -> if (ar) "تم الحفظ تلقائياً" else "Saved"
            "saving" -> if (ar) "جارٍ الحفظ..." else "Saving..."
            "chars_count" -> if (ar) "حرف" else "chars"
            "reading_time" -> if (ar) "دقيقة قراءة تقريباً" else "min read"
            "step_series" -> if (ar) "السلاسل" else "Series"
            "step_books" -> if (ar) "الأجزاء / الكتب" else "Books"
            "step_chapters" -> if (ar) "الفصول" else "Chapters"
            "step_writer" -> if (ar) "المحرر (الكتابة)" else "Writing"
            "project_hub_title" -> if (ar) "مركز المشاريع والإنتاج الروائي" else "Writing & Projects Hub"
            "project_hub_sub" -> if (ar) "اختر نوع المشروع للبدء فوراً في تنظيم عملك الروائي" else "Choose project style to begin your storytelling workspace"
            "type_standalone_novel" -> if (ar) "رواية مفردة (مباشرة)" else "Standalone Novel"
            "type_standalone_novel_desc" -> if (ar) "ابدأ بكتابة رواية واحدة مستقلة، حدد الغلاف والاسم والوصف، ثم انطلق للفصول والمحرر مباشرة." else "Single complete book with its cover, blurb, chapters and instant writing canvas."
            "type_series" -> if (ar) "سلسلة روائية ملحمية" else "Epic Novel Series"
            "type_series_desc" -> if (ar) "مشروع ضخم متعدد الأجزاء؛ غلاف ومعلومات للسلسلة، ثم إدارة متكاملة لأجزاء وكتب السلسلة بأغلفتها وفصولها." else "Multi-book saga with series cover, universe info, and book volumes with their own covers."
            "start_standalone" -> if (ar) "إنشاء رواية مستقلة" else "Create Novel"
            "start_series" -> if (ar) "إنشاء سلسلة جديدة" else "Create Series"
            "cover_image_label" -> if (ar) "غلاف العمل / الكافر" else "Cover Image / Art"
            "cover_placeholder_hint" -> if (ar) "اختر نمط غلاف أو أدخل رابط الصورة" else "Pick cover style or custom artwork"
            "novel_name" -> if (ar) "اسم الرواية" else "Novel Title"
            "novel_summary" -> if (ar) "نبذة وقصة الرواية" else "Novel Synopsis / Blurb"
            "target_words" -> if (ar) "الهدف المقدر للكلمات" else "Target Word Count"
            "series_info_title" -> if (ar) "إعداد وضبط السلسلة" else "Series Configuration"
            "book_info_title" -> if (ar) "إعداد وضبط الجزء / الكتاب" else "Book Volume Configuration"
            "edit_info" -> if (ar) "تعديل البيانات والغلاف" else "Edit Details & Cover"
            "select_series_title" -> if (ar) "السلاسل الروائية" else "Story Series"
            "select_series_sub" -> if (ar) "اختر السلسلة للدخول للأجزاء وإدارتها" else "Select a series to explore and manage volumes"
            "select_book_title" -> if (ar) "أجزاء وكتب السلسلة" else "Series Books & Volumes"
            "select_book_sub" -> if (ar) "اختر الجزء للوصول لفصوله والكتابة" else "Select volume to manage chapters & write"
            "select_chapter_title" -> if (ar) "فصول ومشاهد العمل" else "Chapters & Scenes"
            "select_chapter_sub" -> if (ar) "اختر المشهد أو الفصل للبدء الفوري بالكتابة" else "Pick a scene to dive straight into writing"
            "create_series" -> if (ar) "إنشاء سلسلة جديدة" else "Create New Series"
            "create_book" -> if (ar) "إضافة جزء / كتاب" else "Add New Book"
            "create_chapter" -> if (ar) "إضافة فصل جديد" else "Add New Chapter"
            "create_scene" -> if (ar) "إضافة مشهد جديد" else "Add New Scene"
            "series_name" -> if (ar) "اسم السلسلة" else "Series Name"
            "series_desc" -> if (ar) "نبذة ومعلومات السلسلة" else "Series Description & Lore"
            "book_name" -> if (ar) "عنوان الجزء أو الكتاب" else "Book Title"
            "book_subtitle" -> if (ar) "العنوان الفرعي (مثال: الجزء الأول)" else "Subtitle (e.g. Volume I)"
            "book_desc" -> if (ar) "نبذة وملخص هذا الجزء" else "Volume Summary"
            "chapter_name" -> if (ar) "عنوان الفصل" else "Chapter Title"
            "chapter_desc" -> if (ar) "ملخص أحداث الفصل" else "Chapter Summary"
            "scene_name" -> if (ar) "عنوان المشهد" else "Scene Title"
            "no_series_prompt" -> if (ar) "لا توجد سلاسل حالياً. اضغط لإنشاء أول سلسلة وبدء الكتابة فوراً!" else "No series yet. Tap to create your first series and start writing!"
            "no_books_prompt" -> if (ar) "لا توجد أجزاء في هذه السلسلة. اضغط لإضافة الجزء الأول." else "No books in this series. Tap to add the first volume."
            "no_chapters_prompt" -> if (ar) "لا توجد فصول بعد. اضغط لإضافة أول فصل." else "No chapters yet. Tap to create the first chapter."
            "no_scenes_prompt" -> if (ar) "لا توجد مشاهد في هذا الفصل. اضغط لإضافة مشهد والكتابة فوراً." else "No scenes in this chapter. Tap to create a scene and write."
            "back_to_series" -> if (ar) "الرجوع للسلاسل" else "All Series"
            "back_to_books" -> if (ar) "الرجوع للأجزاء" else "All Books"
            "back_to_chapters" -> if (ar) "الرجوع للفصول" else "All Chapters"
            "quick_jump" -> if (ar) "المسار الحالي" else "Breadcrumb"
            "choose_cover_preset" -> if (ar) "اختر غلاف فني مميز" else "Select Art Theme Cover"

            // 1. Characters Screen
            "char_db_title" -> if (ar) "سجل الشخصيات" else "Character Database"
            "char_registered_count" -> if (ar) "شخصية مسجلة" else "Characters Registered"
            "char_search_hint" -> if (ar) "بحث بالاسم، اللقب، أو الموطن..." else "Search by name, alias, origin..."
            "char_add" -> if (ar) "إضافة شخصية" else "Add Character"
            "char_edit" -> if (ar) "تعديل الشخصية" else "Edit Character"
            "char_name" -> if (ar) "اسم الشخصية" else "Character Name"
            "char_alias" -> if (ar) "الألقاب والأسماء المستعارة (مفصولة بفواصل)" else "Aliases (comma-separated)"
            "char_role" -> if (ar) "الدور الدرامي" else "Role"
            "char_status" -> if (ar) "الحالة الحياتية" else "Status"
            "char_origin" -> if (ar) "الموطن / الأصل" else "Origin / World"
            "char_birth" -> if (ar) "تاريخ أو سنة الميلاد" else "Birth Era / Date"
            "char_death" -> if (ar) "تاريخ أو سنة الوفاة (إن وجد)" else "Death Era / Date (if deceased)"
            "char_abilities" -> if (ar) "القدرات والسمات الخاصة" else "Abilities & Powers"
            "char_notes" -> if (ar) "ملاحظات السيرة والتطور النفسي" else "Bio & Psychology"
            "char_arc" -> if (ar) "القوس الدرامي للشخصية" else "Character Arc"
            "char_relationships" -> if (ar) "العلاقات والروابط" else "Relationships"
            "char_add_rel" -> if (ar) "إضافة علاقة" else "Add Relationship"
            "char_target" -> if (ar) "الشخصية المرتبطة" else "Target Character"
            "char_rel_type" -> if (ar) "نوع العلاقة (حليف، عدو، مرشد...)" else "Relation Type (Ally, Rival, Mentor...)"
            "char_rel_desc" -> if (ar) "وصف الرابط وديناميكية العلاقة" else "Dynamic Description"
            "char_empty" -> if (ar) "لا توجد شخصيات مسجلة بعد. اضغط على زر الإضافة لإنشاء شخصية." else "No characters registered yet. Tap the button to create one."
            "char_appearances" -> if (ar) "المشاهد التي ظهرت بها" else "Scene Appearances"

            // 2. Codex Screen
            "codex_title" -> if (ar) "الموسوعة ومعارف الكون" else "Codex & Universe Lore"
            "codex_entries_count" -> if (ar) "مُدخل موسوعي" else "Lore Entries"
            "codex_search_hint" -> if (ar) "بحث في الموسوعة بالعناوين، الوصف، أو المصطلحات..." else "Search lore by title, summary, or description..."
            "codex_add" -> if (ar) "إضافة مقال موسوعي" else "Add Codex Entry"
            "codex_edit" -> if (ar) "تعديل المُدخل الموسوعي" else "Edit Codex Entry"
            "codex_entry_title" -> if (ar) "عنوان المُدخل" else "Entry Title"
            "codex_summary" -> if (ar) "الملخص السريع" else "Short Summary"
            "codex_description" -> if (ar) "الشرح التفصيلي والمحتوى" else "Detailed Description"
            "codex_rules_laws" -> if (ar) "القوانين والحدود الفيزيائية أو السحرية" else "Rules & Limitations"
            "codex_empty" -> if (ar) "الموسوعة فارغة حالياً. أضف مقالات لتوثيق عالمك وقواعده." else "Codex is currently empty. Add entries to document your lore."

            // 3. Events Screen
            "events_title" -> if (ar) "الأحداث والتسلسل الزمني للقصة" else "Story Events & Chronology"
            "events_count_label" -> if (ar) "حدث زمني موثق" else "Documented Events"
            "events_search_hint" -> if (ar) "بحث في الأحداث بالعنوان، الملخص، أو الموقع..." else "Search events by title, summary, location..."
            "events_add" -> if (ar) "إضافة حدث روائي" else "Add Story Event"
            "events_edit" -> if (ar) "تعديل الحدث" else "Edit Event"
            "events_name" -> if (ar) "عنوان الحدث" else "Event Title"
            "events_summary" -> if (ar) "ملخص الحدث" else "Summary"
            "events_timeline" -> if (ar) "الخط الزمني التابع له" else "Assigned Timeline"
            "events_cosmic_time" -> if (ar) "الوقت الكوني المرجعي" else "Cosmic Timestamp"
            "events_local_time" -> if (ar) "الوقت المحلي التقديري" else "Local Timestamp"
            "events_locations" -> if (ar) "المواقع (مفصولة بفواصل)" else "Locations (comma-separated)"
            "events_empty" -> if (ar) "لا توجد أحداث مسجلة. اضغط لإضافة حدث في التسلسل الزمني." else "No events recorded. Tap to add an event to the timeline."

            // 4. World Rules Screen
            "rules_title" -> if (ar) "قوانين العالم والاتساق المنطقي" else "Universe Laws & Consistency"
            "rules_subtitle" -> if (ar) "تحديد فيزياء العالم واكتشاف تناقضات التسلسل الزمني تلقائياً" else "Define fictional physics and detect timeline contradictions automatically"
            "rules_tab_rules" -> if (ar) "قوانين العالم" else "World Rules"
            "rules_tab_continuity" -> if (ar) "محرك الاتساق" else "Continuity Engine"
            "rules_add" -> if (ar) "إضافة قانون للعالم" else "Add World Rule"
            "rules_edit" -> if (ar) "تعديل القانون" else "Edit World Rule"
            "rules_name" -> if (ar) "اسم القانون أو القاعدة" else "Rule Name"
            "rules_desc" -> if (ar) "الشرح والصيغة الفيزيائية / السحرية" else "Rule Formulation & Description"
            "rules_scope" -> if (ar) "نطاق التأثير (كوكب، مجرة، عالم كامل)" else "Scope of Effect"
            "rules_exceptions" -> if (ar) "الاستثناءات المعروفة" else "Known Exceptions"
            "rules_consequences" -> if (ar) "عواقب خرق هذه القاعدة" else "Consequences of Violation"
            "rules_empty" -> if (ar) "لم يتم تحديد أي قواعد بعد. أنشئ قوانينك لضمان عدم خرق المنطق الروائي." else "No rules defined yet. Create laws to protect your narrative logic."
            "rules_continuity_clean" -> if (ar) "سجل الاتساق نظيف بالكامل! لا توجد مفارقات أو خروقات زمنية." else "Continuity is pristine! Zero paradoxes or causal violations detected."

            // 5. Timeline Screen
            "timeline_title" -> if (ar) "الخطوط الزمنية وتمدد الوقت" else "Timelines & Dilation"
            "timeline_subtitle" -> if (ar) "مزامنة الساعات الكونية مع الساعات المحلية وحساب نسب التمدد" else "Synchronize cosmic and local clocks with automated dilation calculators"
            "timeline_add" -> if (ar) "إضافة خط زمني" else "Add Timeline"
            "timeline_edit" -> if (ar) "تعديل الخط الزمني" else "Edit Timeline"
            "timeline_name" -> if (ar) "اسم الخط الزمني" else "Timeline Name"
            "timeline_multiplier" -> if (ar) "معامل تمدد الوقت (1.0 = سرعة قياسية)" else "Dilation Multiplier (1.0 = standard)"
            "timeline_clock" -> if (ar) "الساعة المرجعية الحالية" else "Current Time Gauge"
            "timeline_calculator" -> if (ar) "حاسبة تمدد الوقت التفاعلية" else "Interactive Dilation Calculator"
            "timeline_input" -> if (ar) "القيمة المدخلة" else "Input Duration"
            "timeline_convert_to_cosmic" -> if (ar) "تحويل: محلي ⬅ كوني" else "Convert: Local -> Cosmic"
            "timeline_convert_to_local" -> if (ar) "تحويل: كوني ⬅ محلي" else "Convert: Cosmic -> Local"
            "timeline_result" -> if (ar) "النتيجة المكافئة:" else "Equivalent Result:"
            "timeline_empty" -> if (ar) "لا توجد خطوط زمنية مسجلة بعد." else "No timelines created yet."

            // 6. Graphs Screen
            "graphs_causal" -> if (ar) "الشبكة السببية للأحداث" else "Causal Graph"
            "graphs_relations" -> if (ar) "شبكة علاقات الشخصيات" else "Character Relations"
            "graphs_add_link" -> if (ar) "ربط سببي جديد" else "Link Events"
            "graphs_select_cause" -> if (ar) "الحدث السبب (المؤدي)" else "Source Event (Cause)"
            "graphs_select_effect" -> if (ar) "الحدث النتيجة (المتأثر)" else "Target Event (Effect)"
            "graphs_link_type" -> if (ar) "نوع الرابط (سبب مباشر، حافز، عاقبة)" else "Relation (Direct Cause, Trigger, Consequence)"
            "graphs_hint" -> if (ar) "اسحب للتنقل في الفضاء السببي • استخدم إصبعين للتكبير والتصغير" else "Drag to pan the causal canvas • Pinch to zoom"
            "graphs_empty" -> if (ar) "أضف أحداثاً أو شخصيات لعرض الخريطة التفاعلية للشبكة." else "Add events or characters to render interactive graph nodes."

            // 7. Global Search Screen
            "search_title" -> if (ar) "البحث الشامل في الكون" else "Omni Search"
            "search_hint_field" -> if (ar) "ابحث عن أي شخصية، مشهد، حدث، قانون، أو مصطلح..." else "Search across scenes, characters, codex, events, and rules..."
            "search_results_found" -> if (ar) "نتائج مطابقة" else "Matches Found"
            "search_no_results" -> if (ar) "لم يتم العثور على نتائج تطابق بحثك." else "No matching entries found."
            "search_type_scene" -> if (ar) "مشهد روائي" else "Scene"
            "search_type_character" -> if (ar) "شخصية" else "Character"
            "search_type_codex" -> if (ar) "موسوعة" else "Codex"
            "search_type_event" -> if (ar) "حدث زمني" else "Event"
            "search_type_rule" -> if (ar) "قانون عالم" else "World Rule"

            else -> key
        }
    }
}
